/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_reverseit_ndksampletest_MainActivity.h"

/*
 * Class:     com_reverseit_ndksampletest_MainActivity
 * Method:    callNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_reverseit_ndksampletest_MainActivity_callNative
  (JNIEnv * env, jobject obj)
  {
    return (*env) -> NewStringUTF(env,"NDK Sample Test !");
  }
//http://sdgsystems.com/blog/using-android-ndk-android-studio/
